filebeat.registry.flush: 10s
setup.template.settings:
  index.number_of_shards: 5

# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  tail_files: true
  paths:
   - /var/log/nginx/*_access.log
   - /var/log/nginx/*_error.log
- type: journald
  id: everything
  seek: cursor
# ================================== General ===================================

fields:
  env: prod
  owner: otus
  responsible: platform_ops
  project: otus

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["192.168.56.205:5044"]
  loadbalance: true
  index: otus

  max_retries: 10
  bulk_max_size: 100
  backoff.init: 15s
  backoff.max: 60s
  timeout: 90
# ================================= Processors =================================
processors:
  - add_host_metadata: ~
  - drop_event:
      when:
        equals:
          syslog.identifier: "sudo"
# ================================== Logging ===================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: info

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publisher", "service".
logging.selectors: ["*"]

