global:
  scrape_interval: 10s

rule_files:
  - "/etc/prometheus/rules/*.rule"

scrape_configs:
  - job_name: 'node-exporter_frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.56.200:9100']
        labels:
          project: 'otus'
          owner: 'otus'
          env: 'prod'
          responsible: 'platform_ops'
          hostname: 'frontend'

  - job_name: 'node-exporter_backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.56.201:9100']
        labels:
          project: 'otus'
          owner: 'otus'
          env: 'prod'
          responsible: 'platform_ops'
          hostname: 'backend'

  - job_name: 'node-exporter_database'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.56.202:9100']
        labels:
          project: 'otus'
          owner: 'otus'
          env: 'prod'
          responsible: 'platform_ops'
          hostname: 'database'

  - job_name: 'node-exporter_monitoring'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.56.204:9100']
        labels:
          project: 'otus'
          owner: 'otus'
          env: 'prod'
          responsible: 'platform_ops'
          hostname: 'monitoring'

  - job_name: 'node-exporter_elk'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.56.205:9100']
        labels:
          project: 'otus'
          owner: 'otus'
          env: 'prod'
          responsible: 'platform_ops'
          hostname: 'elk'

  - job_name: 'node-exporter_mysql'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.56.202:9104']
        labels:
          project: 'otus'
          owner: 'otus'
          env: 'prod'
          responsible: 'platform_ops'
          role: 'mysql'
          hostname: 'datadase'

  - job_name: 'node-exporter_database'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.56.203:9100']
        labels:
          project: 'otus'
          owner: 'otus'
          env: 'prod'
          responsible: 'platform_ops'
          hostname: 'backup'


alerting:
  alertmanagers:
  - static_configs:
      - targets: ['localhost:9093']